### PR TITLE
Secondary y-axis code finished

### PR DESCRIPTION
**Pull request by michaelblight**
I finally worked out how hover is working! I put `--primary` on the main y-axis to differentiate the hiding/showing of the two.

### CODE REVIEW

**Comment by kalkih** [comment]
Looks great, well executed!
Will merge now, might do a new release in a day or two!

Thanks for your contribution! 🎉

**Comment by michaelblight** [comment]
No worries. While I'm on a roll, is there anything else you'd like help with? You've tagged a couple of things with "help wanted". Shall I just pick one or do you have a preference? (I'm going to bed now as it's nearly midnight here and work looms, but I'll check back tomorrow).

**Comment by kalkih** [comment]
Yes, that would be awesome, any of the issues/feature requests really, doesn't matter to me, pick one that you find interesting. 🙂

I'll add you as a collaborator, that way you can work directly against this repo if you'd like, just create a new branch from the dev branch for each feature and then a PR back to the dev branch.

**Comment by michaelblight** [comment]
I just realised I forgot to remove redundant code - main.js lines 721-726. They just need to be deleted, which I can do tonight.

Separately, I tried the dark theme you use, and found the fill with 6 entities graphed was getting a bit over-the-top. So in my local version I've also provided the option to turn it off at an entity level. This probably goes a fair way to handling issue #80. I've got some thoughts on some of the other issues raised too - are you happy for me to just add comments to collaborate? I don't want to throw you under the bus or cause the component to go in a direction you're not happy with.

There's now a lot of `show_*` properties - I will look at the feasibility of moving these to a `show` collection for the entity. I will try to include all the show properties at the card level, so `card.show` is the default for all entities, and `entity.show` can override some/all for a specific entity. Then you can see what you think of it. In my mind it would simplify the usage a bit.

**Comment by michaelblight** [comment]
Damn, I screwed up, sorry. I forgot to create a new branch and I pushed a couple of commits straight to dev. I hope you don't mind.

The first commit was to remove the redundant code mentioned above, which brought with it the introduction of `show_fill`. The second was to fix a bug I introduced when setting the constant for `labels_secondary`. Once I did this, the default became 'hover', and if you didn't have any secondary y-axis data, hovering showed 'infinity' in the labels. I tested these pretty thoroughly, but sorry once again. Maybe it would be better if I went back to forking the repo.

**Comment by kalkih** [comment]
No worries, I don't mind doing small commits directly to dev.

**Comment by michaelblight** [comment]
It looks like something went a bit wrong with the merge of README. The image I added is still pointing to the images folder which was removed, and therefore causes a broken link. However, GitHub thinks there's no difference between my fork and your dev or master branches.

**Comment by kalkih** [comment]
Strange, if the image link is the only thing wrong, do a quick & dirty commit right to master with the correct link if you'd want. 😉

**Pull request merged**
