### PR TITLE
fix: tooltip interval start could be after end

### LINKED ISSUE #181: Problems with "hours_to_show" = float value (particularly < 1.0)
I would like to be able to show 5 min cpu load graphs.
But this means the hours_to_show option should be of type real number (0.083333) instead of integer.
Could this be made possible perhaps?
Love this very nice card btw :)

### PR DESCRIPTION
**Pull request by akloeckner**
* basically: use milliseconds in constants rather than fractions of hours
* also remove strange intervall size of n_points if hours < 1 and points/hour < 1
* also use 1 minute offset for end only when group_by, because that is cosmetics actually

fixes #181

### CODE REVIEW

**Comment by akloeckner** [comment]
@ildar170975 , could you please check, if this solves your issue? According to our contributing guidelines, I'd like to have your approval also for the cleanup part. So, please also check, if your other graphs (especially using group_by) are still fine.

**Comment by ildar170975** [comment]
@akloeckner 
Is it this one?

image

**Comment by ildar170975** [comment]
@akloeckner 
Tested with that js.
[Code from here.](https://github.com/kalkih/mini-graph-card/issues/181#issuecomment-1913344134)
Seems that the issue is fixed.

**Comment by ildar170975** [comment]
But I see this glitch now - no date is shown:

image

**Comment by akloeckner** [comment]
Yes, that's the download I meant. 👍 

Good to see, the original glitch seems fixed. I still don't fully understand why. I think it's something about multiplying small numbers (1/120h interval between points) with big ones (3600000ms in an hour). 🤷 

Let me know, when (and if) you're confident, this could be merged!

**Comment by ildar170975** [comment]
> when (and if) you're confident, this could be merged!

Let's merge it... The more people will test it - the better.
In may old practice (cruise missiles from 1997) even a probably tiny fix needs a full-scope testing, testers should consider a product as a "black box". But this is not a "rocket science" ))

**Comment by akloeckner** [comment]
:-) Agreed!

**Pull request merged**
