### PR TITLE
Move to localForage

### PR DESCRIPTION
**Pull request by bramkragten**
Use indexeddb where supported instead of localStorage to have more space available

### CODE REVIEW

**Comment by kalkih** [comment]
Seems to work great, merging when I get home 👍🏼

**Comment by bramkragten** [comment]
Added `lz-string` but their code is oldskool... needs some cleaning.
https://github.com/bramkragten/mini-graph-card/commit/c3d5f05508d20405ce529c900c319ff23895ea42

**Comment by bramkragten** [comment]
If we want to add compressing, we do need some sort of check if data is compressed or not btw, for being backwards compatible...

**Comment by kalkih** [comment]
Cool, yeah that would be an issue, but I guess we could possibly just switch store name if we switch to compression?
https://github.com/kalkih/mini-graph-card/pull/96/files#diff-1c90ff38a08209f9ebd4d05d1e43358eR25

**Pull request merged**
