### PR TITLE
WIP: Optimize caching

### PR DESCRIPTION
**Pull request by bramkragten**
- use `lz-string` to compress data
- remove unused data from history
- purge stale items from cache once

Needs cleaning of `lz-string`, or external...

### CODE REVIEW

**Comment by kalkih** [comment]
Awesome Bram, ignoring the data we don't use should help quite a bit!
Maybe we could utilize this package?
https://www.npmjs.com/package/lz-string

**Comment by bramkragten** [comment]
yeah, having some problems getting that package to work with rollup... Maybe you can help?

**Comment by kalkih** [comment]
Okay, will take a look tomorrow!

**Comment by kalkih** [comment]
> yeah, having some problems getting that package to work with rollup... Maybe you can help?

Hmm... same, couldn't get the import to work at all 😞

**Comment by kalkih** [comment]
Thinking about moving the lz-string source into another repo, and add it as a dependency instead.
What do you think?

**Comment by bramkragten** [comment]
Yeah fine with me, maybe there is another good lib for it, have not really searched hard...

**Comment by kalkih** [comment]
I did actually look around but didn't really find anything 😞

**Comment by kalkih** [comment]
Moved it now, had some weird issues when trying to import compress/decompress directly from `main.js`, so kept the imports in utils.

**Comment by bramkragten** [comment]
LGTM

**Comment by kalkih** [comment]
Sorry!
Merging when I get home tmrw, or if you wanna merge it into `dev`, I think you should have permission?

**Comment by kalkih** [comment]
Thanks @bramkragten, great work!

**Pull request merged**
