### PR TITLE
Override icon with an image URL

### PR DESCRIPTION
**Pull request by jampez77**
added image attribute to override icon with a URL.

### CODE REVIEW

**Comment by jlsjonas** [comment]
Hey, apparently dev has been force pushed to; could you please rebase onto dev and add a screenshot of what your PR is trying to accomplish? Thanks!

**Comment by jampez77** [comment]
Hi, I've rebased and it all appears fine from what I can see. Here is a screenshot of what I'm trying to acheive.
Screenshot 2022-05-12 at 14 20 55

**Comment by jlsjonas** [comment]
As the branches diverged, the easiest will probably be to reset your branch onto dev and apply your changes again (`git reset --hard origin/dev`)
Note that you will have to force push after committing (`git push --force-with-lease`)

**Comment by jampez77** [comment]
> As the branches diverged, the easiest will probably be to reset your branch onto dev and apply your changes again (`git reset --hard origin/dev`) Note that you will have to force push after committing (`git push --force-with-lease`)
> 
> Note that this is an exceptional circumstance, as master had somehow diverged from dev

Do i need to do this now? I was under the impression I had resolved the conflicts.

**Comment by jlsjonas** [comment]
@jampez77 yes, you're currently requesting to merge 32 commits instead of 1

**Comment by kalkih** [comment]
@jampez77 Tried to push to your dev branch to fix the history but didn't have permission, I've opened a new PR with your commits on, will fix the linting issues and merge it, thanks for your contribution.

See https://github.com/kalkih/mini-graph-card/pull/789

**Pull request closed without merging**
